# Product-related constants
DEFAULT_PRODUCT_LIMIT = 100
MAX_PRODUCT_LIMIT = 500

DEFAULT_PRODUCT_CATEGORY_LIMIT = 25
MAX_PRODUCT_CATEGORY_LIMIT = 100

DEFAULT_PRODUCT_COLLECTION_LIMIT = 100
MAX_PRODUCT_COLLECTION_LIMIT = 500
